import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './footer.css';
import './comic-fix.css';
import './header.css';

const roasts = [
  ["a 'Web3' visionary", "It's Uber but for goldfish, on the blockchain", 'You built a database and called it a revolution. The goldfish deserve better.', 'nobody asked 🐟', '#39FF14', '🤡'],
  ['an ex-consultant', 'AI-powered socks that track your vibe', 'Your TAM is people who hate their own ankles. That is a support group, not a market.', 'synergy overdose 🧦', '#FFFF00', '💀'],
  ["a 'serial' founder", 'Netflix but you pay us to watch our ads', 'You reinvented cable TV and expect a Series A. Bold. Wrong, but bold.', 'delusional confidence 📺', '#FF10F0', '🔥'],
  ['a Stanford dropout', 'An app that reminds you to open other apps', "You've invented a notification with extra steps and a burn rate. Congrats, you're a nuisance with a runway.", 'feature, not a company 📱', '#39FF14', '☠️'],
];
const testimonials = [
  ["I came in with a $50M valuation and left with a therapist's number. 10/10, genuinely.", 'Chad Disruptor', 'Ex-CEO, now a barista', '🤵', '#FFFF00'],
  ["It called my pitch 'a group text I sent by accident.' Rude. Also correct. Also I pivoted.", 'Priya M.', 'Founder → Consultant', '👩‍💻', '#39FF14'],
  ['My cofounder and I both got roasted separately and it said the same thing. We broke up.', "Devon & 'ex-Devon'", 'No longer a team', '💔', '#FF10F0'],
  ["Brutal. Unhinged. Weirdly the best product feedback I've paid $0 for. My VC agreed.", 'Marcus T.', "Serial 'entrepreneur'", '🕶️', '#39FF14'],
  ["It found the flaw my entire seed round was too polite to mention. I owe it my life savings (what's left).", 'Aisha K.', 'Reformed idea-haver', '🧕', '#FFFF00'],
  ['I laughed, I cringed, I learned nothing — exactly as guaranteed. Five stars, deleting LinkedIn.', "Tyler 'Growth' B.", 'Thought leader (former)', '🧢', '#FF10F0'],
];
const pick = (a) => a[Math.floor(Math.random() * a.length)];
function buildRoast({ first, loc, idea }) {
  first = first.trim() || 'founder'; loc = loc.trim() || 'your undisclosed bunker';
  const words = idea.trim().split(/\s+/).filter(Boolean).length;
  const buzz = /\b(ai|blockchain|web3|crypto|nft|disrupt|synerg|platform|uber for|revolution|leverage|scalable|ecosystem)\b/i.test(idea);
  const score = 3 + Math.floor(Math.random() * 22);
  const verdict = words > 0 && words < 12 ? `You wrote ${words} words to describe an entire company. That's not a pitch, ${first}, that's a group text you sent by accident. If you can't be bothered to explain it, we can't be bothered to fund it — and neither will anyone else.` : buzz ? `You stacked every buzzword we've been trained to ignore into one paragraph and called it a strategy. Strip out "AI", "platform", and "disrupt" and there is a suspicious amount of nothing left. This is a Mad Libs, ${first}, not a business.` : `It's not the worst idea we've seen today, which is the meanest thing we can say about it. It solves a problem exactly four people have, three of whom would rather keep the problem than talk to your onboarding flow.`;
  const sections = [
    ["🕳️ The Problem You 'Solved'", '#FFFF00', "Nobody woke up wanting this. You invented a problem so you'd have something to disrupt, then disrupted your own savings account. The market you describe is a Venn diagram of one person: you."],
    ["💸 The 'Business Model'", '#39FF14', '"We’ll figure out monetization later" is not a plan, it’s a hostage note to your future self. Your unit economics work great as long as nobody buys anything and you never pay yourself.'],
    ['🥊 The Competition You Ignored', '#FF10F0', 'Four companies already do this, two are free, and one is owned by a company that could rebuild your entire product over a long lunch. Your moat is a puddle and it’s evaporating.'],
    ['🎪 The Go-To-Market', '#FFFF00', '"It’ll go viral" is the startup equivalent of "I’ll start Monday." Your acquisition strategy is hope, your retention strategy is guilt, and your referral loop is you texting your cousins.'],
    ["🧠 The 'Vision'", '#39FF14', 'You skipped straight to the IPO fantasy and forgot the part where the product has to be good. A $10B TAM slide doesn’t mean anything when your MVP is a Google Form and a dream.'],
  ].sort(() => Math.random() - .5).slice(0, 4);
  return { first, loc, score, verdict, sections, greet: pick([`Sit down, ${first}. This is going to hurt.`, `We read it twice, ${first}. Once was already too much.`, `Congratulations ${first} — you're the reason VCs drink.`]), local: pick([`Ah, ${loc}. Home to roughly forty other people pitching this exact idea from the same coffee shop. Your competitive edge in ${loc} is that you got there before your ex-cofounder did — barely.`, `Building this in ${loc}? Bold. The talent there is either overpriced, overbooked, or already left to build the same thing with better hair. Your local network is three group chats and a LinkedIn connection you've never met.`, `${loc} doesn't need this. We checked. The one investor in ${loc} who'd take the meeting is doing it to be polite and will ghost you before the parking validation. Consider relocating your idea to the trash — it's local and eco-friendly.`]), final: pick(['Our advice: keep the day job, and apologize to the day job for even thinking about leaving.', "This is what honest feedback looks like. Your mom lied. We didn't.", 'Refund your accelerator, hug a stranger, and try again with a completely different brain.', 'The good news: it can only go up from here. The bad news: it won’t.']) };
}
function Marquee({ children, red = false }) { return <div className={'marquee ' + (red ? 'red' : '')}><div>{children} &nbsp; {children}</div></div> }
function App() {
  const [form, setForm] = useState({ idea: '', first: '', loc: '' }); const [result, setResult] = useState(null); const [hover, setHover] = useState(false); const [confetti, setConfetti] = useState([]);
  const onChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = (e) => { e.preventDefault(); setResult(buildRoast(form)); setConfetti(Array.from({ length: 90 }, (_, i) => ({ id: Date.now()+i, left: Math.random()*100, delay: Math.random()*.5, emoji: Math.random()<.35 ? pick(['🔥','💀','🤡','☠️','🚫','📉']) : '' }))); window.scrollTo(0, 0); setTimeout(() => setConfetti([]), 4300); };
  const close = () => { setResult(null); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <main><header className="site-header"><div className="site-header__brand">ROAST<span>.</span>MY<span>.</span>STARTUP</div></header><Marquee>🔥 YOUR STARTUP SUCKS 🔥 GET DESTROYED 🔥 NO REFUNDS 🔥 YOUR MOM LIED TO YOU 🔥 WE FIND WHAT EVERYONE'S TOO POLITE TO MENTION 🔥</Marquee>
    <section className="hero"><i className="spin left">☢️</i><i className="spin rev right">💀</i><div className="terminal">&gt; SYSTEM READY. FEELINGS: NOT FOUND_</div><h1><span className="hero-line hero-line--yellow">YOUR STARTUP SUCKS</span><span className="hero-line hero-line--green">AND WE'LL PROVE IT</span></h1><p className="hero-sub">Get roasted by an AI that doesn't care about your feelings</p><div className="honesty">// yes, this design is intentionally hideous. your startup idea deserves <b>HONESTY, not polish</b>. if we made it pretty you'd trust the compliments. you won't get any.</div><a href="#roastform" className="hero-cta">👇 ROAST ME NOW 👇</a></section>
    <section className="warnings"><div>⚠️ WARNING: This AI will hurt your feelings</div><div>✋ DISCLAIMER: We're not liable if your idea actually sucks</div><div>🎯 GUARANTEE: You'll laugh, cringe & learn nothing</div></section>
    <section id="roastform" className="form-section"><h2>FEED US YOUR "GENIUS"</h2><p>Stop taking advice from people who want to be nice to you. 🔪</p><form onSubmit={submit}><label>💡 Your "revolutionary" idea *</label><textarea name="idea" required rows="4" value={form.idea} onChange={onChange} placeholder="It's like Uber but for... (we're already cringing)"/><div className="grid"><Field label="First name *" name="first" value={form.first} onChange={onChange} placeholder="Chad" green required/><Field label="Last name *" placeholder="Disruptor" green required/></div><Field label="📧 Email (so we know who to blame) *" type="email" placeholder="future.ex.founder@gmail.com" required/><div className="grid"><Select label="Age range *" options={['18-25','26-35','36-45','45+']}/><Select label="Experience *" options={['First time founder','2-3 startups','Serial entrepreneur','Employee','Student','Other']}/></div><div className="grid"><Field label="📍 Location (country/city) *" name="loc" value={form.loc} onChange={onChange} placeholder="Silicon Valley (of course)" required/><Field label="LinkedIn (optional flex)" placeholder="linkedin.com/in/thoughtleader"/></div><button onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)}>{hover ? "😈 I'M READY TO GET DESTROYED 😈" : '🔥 ROAST ME 🔥'}</button><small>By clicking you agree we can and will be mean. 💅</small></form></section>
    <section className="graveyard"><h2>💀 THE GRAVEYARD 💀</h2><p>This is what honest feedback actually looks like. 🔥🔥🔥</p><div className="roast-list">{roasts.map((r,i) => <article className="roast-card" style={{ background:r[4], transform:`rotate(${i%2 ? 1.5 : -1.5}deg)` }} key={r[0]}><b className="badge">{r[5]}</b><small>💬 {r[0]} pitched:</small><q>{r[1]}</q><strong>🔥 {r[2]}</strong><em>— cause of death: {r[3]}</em></article>)}</div><h3>"We find what everyone else is too polite to mention."</h3><p>Your mom says your idea is great. We'll tell you the truth. 💔</p></section>
    <section className="reviews"><h2>⭐ RAVE REVIEWS ⭐</h2><p>People we destroyed had this to say (through tears): 😭</p><div className="review-grid">{testimonials.map((t,i) => <article style={{background:t[4],transform:`rotate(${i%2 ? 1.5 : -1.5}deg)`}} key={t[1]}><small>★★★★★ <span>(5/5, would cry again)</span></small><q>{t[0]}</q><div>{t[3]} <b>{t[1]}</b><em>{t[2]}</em></div></article>)}</div></section>
    <footer><div className="footer-logo">ROAST<span>.</span>MY<span>.</span>STARTUP</div><p className="footer-credit">Built by <b>Vansh Pandita</b> — a founder who also got roasted (and cried, briefly). 😭</p><div className="footer-links"><a href="https://twitter.com/threeoneonetwo" target="_blank" rel="noreferrer">🐦 @threeoneonetwo — we roast people for free, unfortunately</a><a href="https://instagram.com/dailyvansh" target="_blank" rel="noreferrer">📸 @dailyvansh — it's just screenshots of your L's</a></div><small>Privacy policy: We'll sell your roast to the highest bidder <b>(jk)</b> (unless they pay). © 2026 Roast My Startup LLC — a company that will also fail.</small></footer>
    <div className="confetti">{confetti.map(c => <i className="piece" style={{left:`${c.left}%`,animationDelay:`${c.delay}s`, background:c.emoji?'transparent':pick(['#FF0040','#FFFF00','#39FF14','#FF10F0'])}} key={c.id}>{c.emoji}</i>)}</div>
    {result && <div className="overlay"><Marquee red>💀 AUTOPSY COMPLETE 💀 DIAGNOSIS: TERMINAL 💀 NO SURVIVORS 💀</Marquee><div className="autopsy"><div className="big-fire">🔥</div><h2>THE FULL AUTOPSY</h2><p>{result.greet}</p><div className="score"><small>Official Roast Score</small><b>{result.score}<span>/100</span></b><em>{result.score < 10 ? 'CERTIFIED CATASTROPHE ☠️' : result.score < 18 ? 'DEEPLY UNWELL 🤒' : 'TECHNICALLY ALIVE (barely) 🫥'}</em></div><article className="verdict"><h3>🩻 The Verdict</h3><p>{result.verdict}</p></article>{result.sections.map(s => <article className="tear" style={{background:s[1]}} key={s[0]}><h3>{s[0]}</h3><p>{s[2]}</p></article>)}<article className="local"><h3>📍 Local Reality Check — {result.loc}</h3><p>{result.local}</p></article><article className="final">{result.final}</article><div className="actions"><button onClick={close}>← Roast another idea</button><button onClick={close}>😭 I need a hug</button></div><small>no email sent. no mercy given. just this. 💅</small></div></div>}
  </main>;
}
function Field({label,green,...props}) { return <div className="field"><label>{label}</label><input className={green?'green':''} {...props}/></div> }
function Select({label,options}) { return <div className="field"><label>{label}</label><select required defaultValue=""><option value="">— pick —</option>{options.map(x=><option key={x}>{x}</option>)}</select></div> }
createRoot(document.getElementById('root')).render(<App/>);
