import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Analytics } from '@vercel/analytics/react';
import { toJpeg } from 'html-to-image';
import { trackProductEvent } from './product-analytics';
import LegalPage from './legal';
import './styles.css';
import './footer.css';
import './comic-fix.css';
import './header.css';
import './share.css';
import './ai.css';

const roasts = [
  ["a 'Web3' visionary", "It's Uber but for goldfish, on the blockchain", 'You built a database and called it a revolution. The goldfish deserve better.', 'nobody asked 🐟', '#39FF14', '🤡'],
  ['a former consultant', 'Smart socks that track your vibe', 'Your TAM is people who hate their own ankles. That is a support group, not a market.', 'synergy overdose 🧦', '#FFFF00', '💀'],
  ["a 'serial' founder", 'Netflix but you pay us to watch our ads', 'You reinvented cable TV and expect a Series A. Bold. Wrong, but bold.', 'delusional confidence 📺', '#FF10F0', '🔥'],
  ['a Stanford dropout', 'An app that reminds you to open other apps', "You've invented a notification with extra steps and a burn rate. Congrats, you're a nuisance with a runway.", 'feature, not a company 📱', '#39FF14', '☠️'],
];
const testimonials = [
  ["I came in with a $50M valuation and left with a therapist's number. 10/10, genuinely.", 'Chad Disruptor', 'Former CEO, now a barista', '🤵', '#FFFF00'],
  ["It called my pitch 'a group text I sent by accident.' Rude. Also correct. Also I pivoted.", 'Priya M.', 'Founder → Consultant', '👩‍💻', '#39FF14'],
  ['My cofounder and I both got roasted separately and it said the same thing. We broke up.', "Devon and 'former Devon'", 'No longer a team', '💔', '#FF10F0'],
  ["Brutal. Unhinged. Weirdly the best product feedback I've paid $0 for. My VC agreed.", 'Marcus T.', "Serial 'entrepreneur'", '🕶️', '#39FF14'],
  ["It found the flaw my entire seed round was too polite to mention. I owe it my life savings (what's left).", 'Aisha K.', 'Reformed idea enthusiast', '🧕', '#FFFF00'],
  ['I laughed, I cringed, and found one useful truth hiding under the insults. Five stars, deleting LinkedIn.', "Tyler 'Growth' B.", 'Thought leader (former)', '🧢', '#FF10F0'],
];
const pick = (a) => a[Math.floor(Math.random() * a.length)];
function Marquee({ children, red = false }) { return <div className={'marquee ' + (red ? 'red' : '')}><div>{children} &nbsp; {children}</div></div> }
function SiteHeader() { return <header className="site-header"><a className="site-header__brand" href="/">ROAST<span>.</span>MY<span>.</span>STARTUP</a></header> }
function savedRoast() { try { return window.location.pathname === '/roast' ? JSON.parse(sessionStorage.getItem('roast-result')) : null; } catch { return null; } }
function App() {
  const [form, setForm] = useState({ idea: '', founderBackground: '', first: '', age: '', experience: '', loc: '' }); const [result, setResult] = useState(savedRoast); const [route, setRoute] = useState(window.location.pathname); const [hover, setHover] = useState(false); const [confetti, setConfetti] = useState([]); const [formStarted, setFormStarted] = useState(false); const [shareStatus, setShareStatus] = useState(''); const [isSharing, setIsSharing] = useState(false); const [isRoasting, setIsRoasting] = useState(false); const [roastError, setRoastError] = useState(''); const submitted = useRef(false); const autopsyRef = useRef(null);
  const onChange = (e) => { startForm(); setForm({ ...form, [e.target.name]: e.target.value }); };
  const startForm = () => { if (!formStarted) { setFormStarted(true); trackProductEvent('form_started'); } };
  useEffect(() => { const trackAbandon = () => { if (formStarted && !submitted.current) trackProductEvent('form_abandoned'); }; window.addEventListener('pagehide', trackAbandon); return () => window.removeEventListener('pagehide', trackAbandon); }, [formStarted]);
  useEffect(() => { const onPopState = () => setRoute(window.location.pathname); window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState); }, []);
  useEffect(() => { const titles = { '/roast': 'Your Full Autopsy | Roast My Startup', '/privacy': 'Privacy Policy | Roast My Startup', '/terms': 'Terms of Use | Roast My Startup' }; document.title = titles[route] || 'Roast My Startup | Honest Startup Idea Feedback'; const robots = document.querySelector('meta[name="robots"]'); if (robots) robots.content = route === '/roast' ? 'noindex, nofollow' : 'index, follow'; const canonical = document.querySelector('link[rel="canonical"]'); if (canonical) canonical.href = route === '/' ? 'https://roastmystartupnow.vercel.app/' : `https://roastmystartupnow.vercel.app${route}`; }, [route]);
  const submit = async (e) => {
    e.preventDefault();
    submitted.current = true;
    setIsRoasting(true);
    setRoastError('');
    const ideaLength = form.idea.trim().split(/\s+/).filter(Boolean).length;
    const backgroundLength = form.founderBackground.trim().split(/\s+/).filter(Boolean).length;
    trackProductEvent('roast_submitted', { idea_length: ideaLength < 20 ? 'short' : ideaLength < 80 ? 'medium' : 'long', founder_background_length: backgroundLength < 20 ? 'short' : backgroundLength < 80 ? 'medium' : 'long' });
    try {
      const response = await fetch('/api/roast', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ idea: form.idea, founderBackground: form.founderBackground, first: form.first, age: form.age, experience: form.experience, loc: form.loc }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'The roast failed to generate.');
      trackProductEvent('roast_generated', { model: data.model });
      trackProductEvent('roast_viewed');
      setResult(data.roast);
      sessionStorage.setItem('roast-result', JSON.stringify(data.roast));
      window.history.pushState({}, '', '/roast');
      setRoute('/roast');
      setConfetti(Array.from({ length: 90 }, (_, i) => ({ id: Date.now()+i, left: Math.random()*100, delay: Math.random()*.5, emoji: Math.random()<.35 ? pick(['🔥','💀','🤡','☠️','🚫','📉']) : '' })));
      window.scrollTo(0, 0);
      setTimeout(() => setConfetti([]), 4300);
    } catch (error) {
      submitted.current = false;
      setRoastError(error.message || 'The roast caught fire. Try again.');
      trackProductEvent('roast_generation_failed');
    } finally {
      setIsRoasting(false);
    }
  };
  const copyText = async (text) => { if (navigator.clipboard?.writeText) { await navigator.clipboard.writeText(text); } else { const area = document.createElement('textarea'); area.value = text; area.style.position = 'fixed'; area.style.opacity = '0'; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); } setShareStatus('Copied. Your dignity was not.'); setTimeout(() => setShareStatus(''), 2500); };
  const postToX = async () => { const caption = `My startup just scored ${result.score}/100 on ROAST.MY.STARTUP. ${result.verdict.split('.')[0]}. Apparently confidence is not a business model. Think yours survives?`; const probe = new File(['roast'], 'roast-my-startup.jpg', { type: 'image/jpeg' }); const canShareImage = Boolean(navigator.share && navigator.canShare?.({ files: [probe] })); const xWindow = canShareImage ? null : window.open('', '_blank'); if (xWindow) xWindow.opener = null; setIsSharing(true); setShareStatus('Developing photographic evidence…'); try { const dataUrl = await toJpeg(autopsyRef.current, { backgroundColor: '#000', cacheBust: true, pixelRatio: 1, quality: 0.86, filter: (node) => !node.classList?.contains('share-roast') && !node.classList?.contains('actions') && !node.classList?.contains('autopsy-footnote') }); const blob = await (await fetch(dataUrl)).blob(); const file = new File([blob], 'roast-my-startup.jpg', { type: 'image/jpeg' }); if (canShareImage) { await navigator.share({ title: 'My startup got roasted', text: caption, url: 'https://roastmystartupnow.vercel.app', files: [file] }); trackProductEvent('roast_shared', { channel: 'x_image_share' }); setShareStatus('Evidence released. Reputation pending.'); } else { const download = document.createElement('a'); download.href = dataUrl; download.download = file.name; download.click(); const intent = `https://twitter.com/intent/tweet?text=${encodeURIComponent(caption)}&url=${encodeURIComponent('https://roastmystartupnow.vercel.app')}`; if (xWindow) xWindow.location.href = intent; else window.open(intent, '_blank', 'noopener,noreferrer'); trackProductEvent('roast_shared', { channel: 'x_image_download' }); setShareStatus('Screenshot downloaded. Attach the evidence to your prefilled X post.'); } } catch (error) { if (xWindow) xWindow.close(); if (error.name !== 'AbortError') setShareStatus('The screenshot escaped. Try again before it gets funding.'); } finally { setIsSharing(false); } };
  const challengeFriend = async () => { const data = { title: 'Your startup could use some honesty', text: `Mine survived a ${result.score}/100 roast. Submit yours if your ego has health insurance.`, url: 'https://roastmystartupnow.vercel.app' }; trackProductEvent('roast_shared', { channel: navigator.share ? 'native_share' : 'challenge_copy' }); if (navigator.share) { try { await navigator.share(data); } catch (error) { if (error.name !== 'AbortError') await copyText(`${data.text} ${data.url}`); } } else { await copyText(`${data.text} ${data.url}`); } };
  const close = () => { trackProductEvent('roast_another_clicked'); submitted.current = false; setFormStarted(false); setShareStatus(''); setRoastError(''); setResult(null); sessionStorage.removeItem('roast-result'); window.history.pushState({}, '', '/'); setRoute('/'); setTimeout(() => document.getElementById('roastform')?.scrollIntoView({ behavior: 'smooth' }), 0); };
  if (route === '/privacy') return <><Analytics /><LegalPage type="privacy" /></>;
  if (route === '/terms') return <><Analytics /><LegalPage type="terms" /></>;
  if (route === '/roast') return <main><Analytics /><SiteHeader />{result ? <div className="overlay overlay--page"><Marquee red>💀 AUTOPSY COMPLETE 💀 DIAGNOSIS: TERMINAL 💀 NO SURVIVORS 💀</Marquee><div className="autopsy" ref={autopsyRef}><div className="big-fire">🔥</div><h2>THE FULL AUTOPSY</h2><p>{result.greet}</p><div className="score"><small>Official Roast Score</small><b>{result.score}<span>/100</span></b><em>{result.score < 10 ? 'CERTIFIED CATASTROPHE ☠️' : result.score < 18 ? 'DEEPLY UNWELL 🤒' : 'TECHNICALLY ALIVE (barely) 🫥'}</em></div><article className="verdict"><h3>{result.verdictTitle || '🩻 The Core Delusion'}</h3><p>{result.verdict}</p></article>{result.sections.map(s => <article className="tear" style={{background:s[1]}} key={s[0]}><h3>{s[0]}</h3><p>{s[2]}</p></article>)}<article className="local"><h3>{result.localTitle || '📍 Local Reality Check'}: {result.loc}</h3><p>{result.local}</p></article><article className="final">{result.final}</article>{result.sources?.length > 0 && <section className="roast-sources"><h3>🧾 RECEIPTS</h3><ol>{result.sources.map((source, index) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">[{index + 1}] {source.title}</a></li>)}</ol></section>}<section className="share-roast"><h3>📢 SHARE YOUR L WITH THE WORLD</h3><p>Misery loves company. Drag your friends down here too. 😈</p><div className="share-roast__buttons"><button className="share-roast__x" type="button" onClick={postToX} disabled={isSharing}>{isSharing ? '📸 DEVELOPING EVIDENCE…' : '🐦 POST MY ROAST ON X'}</button><button className="share-roast__challenge" type="button" onClick={challengeFriend}>📲 CHALLENGE A FRIEND</button></div><small aria-live="polite">{shareStatus}</small></section><div className="actions"><button onClick={close}>← Roast another idea</button><button onClick={close}>😭 I need a hug</button></div><small className="autopsy-footnote">no email sent. no mercy given. just this. 💅</small></div></div> : <section className="missing-roast"><h1>NO BODY FOUND 💀</h1><p>This autopsy expired with your browser session. Submit the startup again so we can kill it properly.</p><button type="button" onClick={close}>← Go get roasted</button></section>}<div className="confetti">{confetti.map(c => <i className="piece" style={{left:`${c.left}%`,animationDelay:`${c.delay}s`, background:c.emoji?'transparent':pick(['#FF0040','#FFFF00','#39FF14','#FF10F0'])}} key={c.id}>{c.emoji}</i>)}</div></main>;
  return <main><Analytics /><SiteHeader /><Marquee>🔥 YOUR STARTUP SUCKS 🔥 GET DESTROYED 🔥 NO REFUNDS 🔥 YOUR MOM LIED TO YOU 🔥 WE FIND WHAT EVERYONE'S TOO POLITE TO MENTION 🔥</Marquee>
    <section className="hero"><i className="spin left">☢️</i><i className="spin rev right">💀</i><div className="terminal">&gt; SYSTEM READY. FEELINGS: NOT FOUND_</div><h1><span className="hero-line hero-line--yellow"><span>YOUR</span><span>STARTUP</span><span>SUCKS</span></span><span className="hero-line hero-line--green"><span>AND</span><span>WE'LL</span><span>PROVE IT</span></span></h1><p className="hero-sub">Get honest feedback that doesn't care about your feelings</p><div className="honesty">// yes, this design is intentionally hideous. your startup idea deserves <b>HONESTY, not polish</b>. if we made it pretty you'd trust the compliments. you won't get any.</div><a href="#roastform" className="hero-cta">👇 ROAST ME NOW 👇</a></section>
    <section className="warnings"><div>⚠️ WARNING: This will hurt your feelings</div><div>🔎 AI CAN BE WRONG: Verify facts before betting the runway</div><div>🎯 PROMISE: You'll laugh, cringe & find the useful bit hiding inside</div></section>
    <section id="roastform" className="form-section"><h2>FEED US YOUR "GENIUS"</h2><p>Stop taking advice from people who want to be nice to you. 🔪</p><form onSubmit={submit}><label>💡 Your "revolutionary" idea *</label><textarea name="idea" required rows="4" value={form.idea} onChange={onChange} placeholder="It's like Uber but for... (we're already cringing)"/><div className="field"><label>🧠 Founder background (your LinkedIn fan fiction) *</label><textarea name="founderBackground" required rows="4" value={form.founderBackground} onChange={onChange} placeholder="Former McKinsey? College dropout? Your dad knows a VC? Tell us what you've built, studied, survived, or dramatically resigned from."/></div><Field label="First name *" name="first" value={form.first} onChange={onChange} placeholder="Chad" green required/><div className="grid"><Select label="Age range *" name="age" value={form.age} onChange={onChange} options={['18 to 25','26 to 35','36 to 45','45+']}/><Select label="Experience *" name="experience" value={form.experience} onChange={onChange} options={['First time founder','2 to 3 startups','Serial entrepreneur','Employee','Student','Other']}/></div><Field label="📍 Location (country/city) *" name="loc" value={form.loc} onChange={onChange} placeholder="Silicon Valley (of course)" required/><button disabled={isRoasting} onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)}>{isRoasting ? '🔥 THE ROAST IS COOKING… 🔥' : hover ? "😈 I'M READY TO GET DESTROYED 😈" : '🔥 ROAST ME 🔥'}</button>{roastError && <strong className="roast-error" role="alert">{roastError}</strong>}<small>By clicking, you confirm you are 18+ and agree to the <a href="/terms">Terms</a> and <a href="/privacy">Privacy Policy</a>. We can and will be mean. 💅</small></form></section>
    <section className="graveyard"><h2>💀 THE GRAVEYARD 💀</h2><p>This is what honest feedback actually looks like. 🔥🔥🔥</p><div className="roast-list">{roasts.map((r,i) => <article className="roast-card" style={{ background:r[4], transform:`rotate(${i%2 ? 1.5 : -1.5}deg)` }} key={r[0]}><b className="badge">{r[5]}</b><small>💬 {r[0]} pitched:</small><q>{r[1]}</q><strong>🔥 {r[2]}</strong><em>Cause of death: {r[3]}</em></article>)}</div><h3>"We find what everyone else is too polite to mention."</h3><p>Your mom says your idea is great. We'll tell you the truth. 💔</p></section>
    <section className="reviews"><h2>⭐ FICTIONAL ROAST EXAMPLES ⭐</h2><p>Made up founders. Real examples of the tone. No imaginary customers were harmed. 😭</p><div className="review-grid">{testimonials.map((t,i) => <article style={{background:t[4],transform:`rotate(${i%2 ? 1.5 : -1.5}deg)`}} key={t[1]}><small>FICTIONAL EXAMPLE • ★★★★★ <span>(5/5, would cry again)</span></small><q>{t[0]}</q><div>{t[3]} <b>{t[1]}</b><em>{t[2]}</em></div></article>)}</div></section>
    <footer><div className="footer-logo">ROAST<span>.</span>MY<span>.</span>STARTUP</div><p className="footer-credit">Built by <b>Vansh Pandita</b>. A founder who also got roasted (and cried, briefly). 😭</p><div className="footer-links"><a href="https://twitter.com/threeoneonetwo" target="_blank" rel="noreferrer">🐦 @threeoneonetwo: we roast people for free, unfortunately</a><a href="https://instagram.com/dailyvansh" target="_blank" rel="noreferrer">📸 @dailyvansh: it's just screenshots of your L's</a></div><div className="footer-legal"><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Use</a><span>© 2026 Roast My Startup. An independent project by Vansh Pandita.</span></div></footer>
    <div className="confetti">{confetti.map(c => <i className="piece" style={{left:`${c.left}%`,animationDelay:`${c.delay}s`, background:c.emoji?'transparent':pick(['#FF0040','#FFFF00','#39FF14','#FF10F0'])}} key={c.id}>{c.emoji}</i>)}</div>
  </main>;
}
function Field({label,green,...props}) { return <div className="field"><label>{label}</label><input className={green?'green':''} {...props}/></div> }
function Select({label,options,...props}) { return <div className="field"><label>{label}</label><select required {...props}><option value="">Pick one</option>{options.map(x=><option key={x} value={x}>{x}</option>)}</select></div> }
createRoot(document.getElementById('root')).render(<App/>);
